name: kocek
description: Kocek Ewallet - Aplikasi dompet digital untuk membantu kebutuhan transaksi sehari-hari.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides:
  connectivity_plus: 4.0.1
  http: 1.1.0
  intl: 0.18.1

dependencies:
  animations: ^2.0.8

  auto_route: ^7.8.4
  auto_size_text: 3.0.0
  custom_sliding_segmented_control: ^1.8.1
  data_channel: 2.0.0+1
  dio: ^5.3.3
  dynamic_color: ^1.6.8
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: 2.4.1
  fresh_dio: ^0.4.1
  fresh_graphql: 0.5.2
  get_it: ^7.6.4
  graphql_flutter: 5.1.2
  http: 1.1.0
  hydrated_bloc: 9.1.2
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  internet_connection_checker_plus: ^2.1.0
  intl: 0.18.1
  json_annotation: 4.8.1
  json_theme: ^6.3.0
  keframe: 3.0.0
  logger: ^2.0.2+1
  material_design_icons_flutter: 7.0.7296
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  permission_handler_web: 0.0.2
  pretty_dio_logger: 1.3.1
  reactive_forms: ^16.1.1
  rounded_loading_button: 2.1.0
  sentry_dart_plugin: ^1.6.2
  sentry_dio: ^7.11.0
  sentry_flutter: ^7.11.0
  shimmer: 3.0.0
  slang: ^3.25.0
  spring_button: 2.0.0
  statsfl: 2.3.0
  styled_text: ^8.1.0
  universal_platform: 1.0.0+1
  url_launcher: ^6.2.1
  url_strategy: 0.2.0
  web_socket_channel: 2.4.0
  flutter_svg: ^2.0.8

dev_dependencies:
  artemis: ^7.13.1

  # The "very_good_analysis & dart_code_metrics" package below contains a set of
  # recommended encourage good coding practices. The lint set provided by the package is
  # lints to activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  golden_toolkit: 0.15.0
  injectable_generator: ^2.4.1
  json_serializable: 6.7.1
  mocktail: ^1.0.1
  mocktail_image_network: ^1.0.0
  r_resources: 1.0.1
  slang_build_runner: ^3.25.0
  slang_flutter: ^3.25.0
  change_app_package_name: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/
    - assets/configs/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
          weight: 200

# Native splash screen settings.
flutter_native_splash:
  color: "#1ABEF1"
  image: assets/images/splash/kocek_splash_logo.png
  color_dark: "#1ABEF1"
  image_dark: assets/images/splash/kocek_splash_logo.png
  android_12:
    image: assets/images/splash/kocek_splash_logo.png
    icon_background_color: "#1ABEF1"
    image_dark: assets/images/splash/kocek_splash_logo.png
    icon_background_color_dark: "#1ABEF1"
  fullscreen: false
