name: commons
description: The commons of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  deps:
    path: ../../deps/
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  pyramid_lint: ^1.1.0
