name: app
description: The main app of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  deps:
    path: ../infrastructure/deps
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ../infrastructure/design/assets/shapes/variant-one-colored/
    - ../infrastructure/design/assets/shapes/variant-two-uncolored/
    - ../infrastructure/design/assets/shapes/variant-three-3d/
  fonts:
  - family: SpaceGrotesk
    fonts:
      - asset: ../infrastructure/design/assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
        weight: 700
      - asset: ../infrastructure/design/assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
        weight: 500
      - asset: ../infrastructure/design/assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
        weight: 400
      - asset: ../infrastructure/design/assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
        weight: 300
  - family: FogtwoNo5
    fonts:
      - asset: ../infrastructure/design/assets/fonts/FogtwoNo5/FogtwoNo5-Regular.ttf
        weight: 400