name: app
description: The main app of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  pyramid_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - ../design/assets/images/
  fonts:
  - family: Nunito
    fonts:
      - asset: ../design/assets/fonts/Nunito/Nunito-Bold.ttf
        weight: 700
      - asset: ../design/assets/fonts/Nunito/Nunito-Medium.ttf
        weight: 500
      - asset: ../design/assets/fonts/Nunito/Nunito-Regular.ttf
        weight: 400
      - asset: ../design/assets/fonts/Nunito/Nunito-Light.ttf
        weight: 300