name: locator
description: The locator of dependency injection for flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
