name: flavors
description: The flavors of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  deps:
    path: ../../deps/
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  injectable_generator: ^2.4.1
  pyramid_lint: ^1.2.0
