targets:
  $default:
    builders:
      # Envied
      envied_generator:
        generate_for:
          include:
            - lib/flavors/*.dart
      # Freezed
      freezed:
        options:
          map: false
          when:
            when: false
            maybe_when: false
            when_or_null: true
        generate_for:
          include:
            - lib/networking/**/*.model.dart
            - lib/theming/**/*.model.dart
            - lib/theming/**/*.cubit.dart
      # Json Serializable
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          explicit_to_json: true
          field_rename: snake
          include_if_null: true
        generate_for:
          include:
            - lib/networking/**/*.model.dart
            - lib/theming/**/*.model.dart
      # Slang
      slang_build_runner:
        options:
          fallback_strategy: base_locale
          input_directory: lib/core/i18n
          output_directory: lib/core/i18n
          output_file_name: translations.g.dart
          translate_var: tr
          key_case: camel
          key_map_case: camel
          param_case: camel
          flat_map: false
        generate_for:
          include:
            - lib/core/i18n/*
      # Injectable
      injectable_generator:
        generate_for:
          include:
            - lib/_di/*.dart
            - lib/analytics/**/*.dart
            - lib/networking/**/*.dart
            - lib/storage/**/*.dart
            - lib/theming/**/*.dart