name: deps
description: The deps of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analytics:
    path: ../core/analytics
  auth:
    path: ../../features/auth
  auto_route: ^7.8.4
  awesome_extensions: ^2.0.10
  design:
    path: ../design
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  envied: ^0.5.1
  flavors:
    path: ../core/flavors
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hydrated_bloc: ^9.1.2
  injectable: ^2.3.2
  internet_connection_checker_plus: ^2.1.0
  json_theme: ^6.4.0
  locator:
    path: ../locator
  networking:
    path: ../core/networking
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  sentry_flutter: ^7.13.1
  storage:
    path: ../core/storage
  styled_text: ^8.1.0
  talker_dio_logger: ^2.3.1
  talker_flutter: ^3.5.4
  theme_tailor_annotation: ^2.0.2
  theming:
    path: ../core/theming
  uicons: ^1.0.1
  widgetbook: ^3.4.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
