name: networking
description: The networking implementation of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  deps:
    path: ../../deps/
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.1.0
  talker_dio_logger: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
